name: Daily Script
on:
  schedule:
    - cron: '* * * * *'
   
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        
      - name: Git Commands
        run: |
       
             cd C:/Users/ACER
     
             git pull https://github.com/steja6872/v2-new-git.git
             
             cp C:/Users/ACER/Desktop/factorial.java C:/Users/ACER/v2-new-git
             git add .
             git commit -m "Add Java file"
             git status
             git remote remove origin
             git remote add origin https://github.com/steja6872/v2-new-git.git
             git push -u origin master
