name: Daily Script
on:
  schedule:
    - cron: '31 13 * * *'
   
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        
      - name: Git Commands
        run: |
             mkdir C:/Users/ACER/v2-new-git
             cd C:/Users/ACER/v2-new-git
             git init
             git pull https://github.com/steja6872/v2-new-git.git
             git remote add origin https://github.com/steja6872/v2-new-git.git
             cp C:/Users/ACER/Desktop/factorial.java C:/Users/ACER/v2-new-git
             git add factorial.java
             git commit -m "Add Java file"
             git status
             git push -u origin master
